[workspace]
resolver = "2"
members = [
    "crates/slate-proto",
    "crates/slated",
    "crates/slash",
    "crates/slate",
    "crates/slate-desktop",
]

[workspace.package]
version = "0.0.12"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/BenchGrid-dev/slate"
rust-version = "1.85"

[workspace.dependencies]
slate-proto = { path = "crates/slate-proto" }
